### ISSUE TITLE
Species - Creacion de un metodo para obtener una especie en particular

### ISSUE THREAD

**Issue by GastonZianni** [SantaPesca/species#2]
Metodo: GET,
nombre: .../species/{idSpecie},
Resultado esperado:
```
{
    name: <NombreEspecie> (string),
    scientificName: <NombreCientificoEspecie> (string),
    description: <DescripcionEspecie> (string),
    maxWeight: <PresoMaximo> (string),
    maxLength: <LongitudMaxima> (string),
    photo: <UrlFotoBucket> (string),
    canBeFished: <En veda o no> (Boolean - false si esta en veda. true en caso contrario)
}
```

**Queda por definir el resto de los atributos que va a tener una especie en particular, en el mock-up hay un par mas pero habria que ponernos de acuerdo**

**Comment by GastonZianni** [comment]
https://www.magyp.gob.ar/sitio/areas/pesca_continental/especies/

**Comment by GastonZianni** [comment]
http://www.pescaargentina.com.ar/pesca-deportiva/santa_fe/

**Comment by GastonZianni** [comment]
http://sentilapesca.com.ar/santa-fe-reglamento-pesca-deportiva

**Comment by midestefanis** [comment]
Cambié:
maxWeight: <PresoMaximo> (string),
maxLength: <LongitudMaxima> (string),
